#!/usr/bin/env node
/* ══════════════════════════════════════════════════════════════════════
   selfhost-fonts.mjs — remove the render-blocking third-party font request

   PROBLEM
   Every page blocks rendering on this:

     <link href="https://fonts.googleapis.com/css2?family=Playfair+Display…"
           rel="stylesheet">

   Nothing paints until that returns. It is a separate origin, so the browser
   pays DNS + TLS + round trip before it even learns which font files to get,
   and only then starts fetching them. Lighthouse measured it as the largest
   single item on the page: "Render-blocking requests, est. savings 1,990 ms".

   FIX
   Download the exact same woff2 files, serve them from our own origin, and
   replace the remote stylesheet with a local one. The connection is already
   open, so the round trip disappears.

   NOTHING VISIBLE CHANGES. Identical font files, identical families, weights
   and styles, and font-display:swap is preserved exactly as Google sets it.
   This is not a substitution or a fallback — it is the same bytes from a
   closer place.

   Only the latin, latin-ext and arabic subsets are kept. Google also serves
   cyrillic, greek and vietnamese; those never match a character on this site,
   so they only bloat the CSS.

     node selfhost-fonts.mjs            # download + rewrite
     node selfhost-fonts.mjs --check    # report only
   ══════════════════════════════════════════════════════════════════════ */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');
const FONT_DIR = path.join(ROOT, 'assets/fonts');
const CSS_OUT = path.join(ROOT, 'assets/css/fonts.css');

const GOOGLE_CSS =
  'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400' +
  '&family=Inter:wght@300;400;500;600;700&family=Tajawal:wght@300;400;500;700&display=swap';

/* A modern desktop UA makes Google serve woff2, the smallest format every
   browser we care about supports. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const KEEP_SUBSETS = ['latin', 'latin-ext', 'arabic'];

const css = await (await fetch(GOOGLE_CSS, { headers: { 'User-Agent': UA } })).text();

/* Google emits "/* latin *\/" before each @font-face, which is how we know
   which subset a block belongs to. */
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
  .map((m) => ({ subset: m[1], body: m[2] }));

const kept = blocks.filter((b) => KEEP_SUBSETS.includes(b.subset));
console.log(`@font-face blocks: ${blocks.length} total, keeping ${kept.length} (${KEEP_SUBSETS.join(', ')})`);

if (!CHECK_ONLY) fs.mkdirSync(FONT_DIR, { recursive: true });

let out = `/* Self-hosted Google Fonts. Generated by tools/selfhost-fonts.mjs.
   Same woff2 files Google serves, from our own origin, so the render-blocking
   third-party round trip disappears. Do not edit by hand — re-run the tool. */\n\n`;
let downloaded = 0, bytes = 0, reused = 0;

for (const { subset, body } of kept) {
  const url = body.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)?.[1];
  if (!url) continue;

  const family = body.match(/font-family:\s*'([^']+)'/)?.[1] || 'font';
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1] || '400';
  const style = body.match(/font-style:\s*(\w+)/)?.[1] || 'normal';
  const name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
  const dest = path.join(FONT_DIR, name);

  if (!CHECK_ONLY) {
    if (fs.existsSync(dest)) reused++;
    else {
      const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
      fs.writeFileSync(dest, buf);
      downloaded++; bytes += buf.length;
    }
  }

  out += `/* ${subset} */\n` + body.replace(/url\(https:\/\/fonts\.gstatic\.com\/[^)]+\)`?/, `url(/assets/fonts/${name})`) + '\n\n';
}

const kb = (n) => (n / 1024).toFixed(0);
console.log(`downloaded ${downloaded} woff2 files (${kb(bytes)} KB)${reused ? `, ${reused} already present` : ''}`);
console.log(`fonts.css: ${kb(Buffer.byteLength(out))} KB (Google's was ${kb(Buffer.byteLength(css))} KB)`);

if (!CHECK_ONLY) fs.writeFileSync(CSS_OUT, out, 'utf8');

/* ── Swap the remote stylesheet for the local one on every page ──────── */
const SKIP = ['.git', 'admin', 'node_modules', 'tools', 'backend', 'templates', 'seo-autoblog', 'ar'];
function html(dir = ROOT, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || e.name.startsWith('_')) continue;
    const abs = path.join(dir, e.name);
    if (e.isDirectory()) { if (!SKIP.includes(e.name)) html(abs, acc); }
    else if (e.name.endsWith('.html')) acc.push(abs);
  }
  return acc;
}

let patched = 0;
for (const f of html()) {
  const s = fs.readFileSync(f, 'utf8');
  // Replace the Google stylesheet link; drop the now-pointless preconnects.
  let o = s
    .replace(/[ \t]*<link href="https:\/\/fonts\.googleapis\.com\/css2[^"]*"[^>]*>\s*\n?/g,
             '  <link rel="stylesheet" href="/assets/css/fonts.css">\n')
    .replace(/[ \t]*<link rel="preconnect" href="https:\/\/fonts\.(googleapis|gstatic)\.com"[^>]*>\s*\n?/g, '');
  if (o !== s) { if (!CHECK_ONLY) fs.writeFileSync(f, o, 'utf8'); patched++; }
}
console.log(`pages pointed at the local stylesheet: ${patched}`);
console.log(CHECK_ONLY ? '\nCheck only. Nothing written.' : '\nDone. Re-run build:ar so the Arabic twins pick it up.');
