#!/usr/bin/env node
/* ══════════════════════════════════════════════════════════════════════
   split-i18n.mjs — cut the 1 MB dictionary off the critical path

   WHY
   assets/js/i18n.js is ~1.08 MB, and ~1.05 MB of that is the TRANSLATIONS
   object. Every page downloads and parses all of it before the navbar and
   footer appear.

   Since build-ar.mjs bakes the Arabic into /ar/ as static HTML, that
   dictionary no longer changes a single word of page text — verified: on
   every page checked, the rendered text already equals the dictionary value
   for all data-i18n elements. The 1 MB is doing no work at render time.

   WHAT THIS PRODUCES
     assets/js/i18n-core.js     ~30 KB — navbar, footer, toggle, engine, and
                                only the strings the injected chrome uses
     assets/js/i18n-strings.js  ~1 MB — the full dictionary, fetched ONLY if
                                something asks for a key the core lacks

   Nothing is thrown away. If any runtime code (dashboard content, dynamic
   doctor cards) requests a key outside the core set, the core lazy-loads the
   full file and re-applies. Worst case is the old behaviour, one tick later.

   i18n.js is left untouched, so it stays the single source you edit. Re-run
   this after changing it.

     node split-i18n.mjs            # write both files
     node split-i18n.mjs --check    # report sizes only
   ══════════════════════════════════════════════════════════════════════ */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'assets/js/i18n.js');
const CHECK_ONLY = process.argv.includes('--check');

/* Keys the runtime asks for by name via I18N.t(). These have fallbacks in
   dynamic-content.js, but including them avoids a needless lazy fetch. */
const RUNTIME_KEYS = [
  'doctors.viewprofile',
  'services.readmore',
  'bs.emtone.doc.view',
];

const src = fs.readFileSync(SRC, 'utf8');
const tStart = src.indexOf('const TRANSLATIONS');
const tEnd = src.indexOf('const I18N');
if (tStart < 0 || tEnd < 0) throw new Error('Could not locate TRANSLATIONS / I18N in i18n.js');

const header = src.slice(0, tStart);          // nav + footer HTML, injection
const literal = src.slice(tStart, tEnd).trim()
  .replace(/^const\s+TRANSLATIONS\s*=\s*/, '').replace(/;\s*$/, '');
const engine = src.slice(tEnd);               // the I18N object + init

// eslint-disable-next-line no-eval
const T = eval('(' + literal + ')');

/* Core key set: everything the injected chrome renders, plus runtime keys. */
const chromeKeys = new Set([...header.matchAll(/data-i18n(?:-html|-placeholder)?="([^"]+)"/g)].map(m => m[1]));
RUNTIME_KEYS.forEach(k => chromeKeys.add(k));

const core = { en: {}, ar: {} };
for (const k of chromeKeys) {
  if (T.en[k] != null) core.en[k] = T.en[k];
  if (T.ar[k] != null) core.ar[k] = T.ar[k];
}

/* ── i18n-strings.js — the full dictionary, loaded on demand ─────────── */
const stringsFile =
`/* Full translation dictionary. Generated by tools/split-i18n.mjs — do not
   edit by hand; edit assets/js/i18n.js and re-run the build.
   Loaded lazily by i18n-core.js, only when a key outside the core set is
   requested. Most page views never fetch this file. */
window.HC_STRINGS = ${JSON.stringify(T)};
if (window.HC_I18N_READY) window.HC_I18N_READY();
`;

/* ── i18n-core.js — chrome + engine + lazy loader ────────────────────── */
const coreDict =
`/* Only the strings the injected navbar and footer need. The rest live in
   i18n-strings.js and are fetched on demand. Generated — do not edit. */
const CORE_STRINGS = ${JSON.stringify(core)};

/* TRANSLATIONS starts as the core set and is replaced by the full dictionary
   if it ever gets loaded. Everything downstream reads it exactly as before. */
let TRANSLATIONS = CORE_STRINGS;
let HC_FULL_LOADED = false, HC_FULL_LOADING = false;

/* Pull in the full dictionary, then re-apply so any element that was waiting
   on a missing key gets its text. Safe to call repeatedly. */
function hcLoadFullStrings() {
  if (HC_FULL_LOADED || HC_FULL_LOADING) return;
  HC_FULL_LOADING = true;
  window.HC_I18N_READY = function () {
    TRANSLATIONS = window.HC_STRINGS || TRANSLATIONS;
    HC_FULL_LOADED = true; HC_FULL_LOADING = false;
    try { I18N.apply(); } catch (e) {}
    document.dispatchEvent(new CustomEvent('i18n:full-loaded'));
  };
  var s = document.createElement('script');
  s.src = '/assets/js/i18n-strings.js';
  s.async = true;
  s.onerror = function () { HC_FULL_LOADING = false; };
  document.head.appendChild(s);
}
window.hcLoadFullStrings = hcLoadFullStrings;
`;

/* In apply(), a key that is missing from the core set means dynamic content
   is on the page. Trigger the lazy load rather than falling back to English. */
const T_OLD = ' t(key) {\n const lang = this.current();\n return (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) || key;\n },';
const T_NEW = ' t(key) {\n const lang = this.current();\n const v = TRANSLATIONS[lang] && TRANSLATIONS[lang][key];\n if (v != null) return v;\n // Unknown key: the full dictionary may have it. Fetch it once, then re-apply.\n if (!HC_FULL_LOADED) hcLoadFullStrings();\n return key;\n },';
let patchedEngine = engine.replace(T_OLD, T_NEW);

/* apply() walks every data-i18n element. On a statically built page the text
   is already correct, so a key outside the core set means "nothing to do" —
   NOT "go fetch 1.2 MB". Give apply() a non-fetching lookup; the existing
   `translated !== key` guard then leaves the static text untouched.
   Explicit I18N.t() calls from runtime code still trigger the lazy load. */
const PEEK = ' peek(key) {\n const lang = this.current();\n const v = TRANSLATIONS[lang] && TRANSLATIONS[lang][key];\n return v == null ? key : v;\n },\n\n';
patchedEngine = patchedEngine.replace(T_NEW, PEEK + T_NEW);
const APPLY_BEFORE = 'const translated = this.t(key);';
const applyCount = patchedEngine.split(APPLY_BEFORE).length - 1;
if (applyCount !== 3) throw new Error('expected 3 this.t(key) sites inside apply(), found ' + applyCount);
// only rewrite the three inside apply(), which come after the t()/peek() defs
const idx = patchedEngine.indexOf(' apply() {');
patchedEngine = patchedEngine.slice(0, idx) +
  patchedEngine.slice(idx).split(APPLY_BEFORE).join('const translated = this.peek(key);');
if (patchedEngine === engine) throw new Error('Could not patch t() — engine source changed');

const coreFile = header + coreDict + '\n' + patchedEngine;

const kb = (s) => (Buffer.byteLength(s, 'utf8') / 1024).toFixed(0);
console.log(`i18n.js (source)   : ${kb(src)} KB`);
console.log(`i18n-core.js       : ${kb(coreFile)} KB   (${Object.keys(core.en).length} core keys)`);
console.log(`i18n-strings.js    : ${kb(stringsFile)} KB  (lazy)`);
console.log(`\nremoved from every page load: ${(Buffer.byteLength(src) - Buffer.byteLength(coreFile)) / 1024 | 0} KB`);

if (!CHECK_ONLY) {
  fs.writeFileSync(path.join(ROOT, 'assets/js/i18n-core.js'), coreFile, 'utf8');
  fs.writeFileSync(path.join(ROOT, 'assets/js/i18n-strings.js'), stringsFile, 'utf8');
  console.log('\nWritten. Pages must reference i18n-core.js instead of i18n.js.');
} else {
  console.log('\nCheck only. Nothing written.');
}
